name: bcz
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - numpy
  - ca-certificates
  - openssl
  - cffi
  - pillow
  - natsort
  - pyquaternion
  - hydra-core
  - pytorch==1.13.1
  - torchvision==0.14.1
  - torchaudio==0.13.1
  - pytorch-cuda=11.7
  - sentence-transformers
  - certifi
  - absl-py
  - transforms3d
  - wandb