environment:
  _target_: rlbench.Environment
  action_mode:
    _target_: rlbench.action_modes.action_mode.MoveArmThenGripper
    arm_action_mode:
      _target_: rlbench.action_modes.arm_action_modes.EndEffectorPoseViaIK
    gripper_action_mode:
      _target_: rlbench.action_modes.gripper_action_modes.Discrete
  dataset_root: data
  obs_config:
    _target_: rlbench.observation_config.ObservationConfig
  headless: False

task: rlbench.tasks.reach_target.ReachTarget

demos:
  amount: 10
  live_demos: False
  image_paths: True
  max_attempts: 1
  random_selection: False
  from_episode_number: 0
