train_dataset:
  _target_: lib.demo_dataset.DemoDataset
  variations: [0]
  demos_config:
    amount: 100
    image_paths: True
    dataset_root: data
    task_name: reach_target
    obs_config:
      _target_: rlbench.ObservationConfig
    random_selection: False
    from_episode_number: 0
  action_mode:
    _target_: rlbench.action_modes.action_mode.MoveArmThenGripper
    arm_action_mode:
      _target_: rlbench.action_modes.arm_action_modes.EndEffectorPoseViaIK
      absolute_mode: False
    gripper_action_mode:
      _target_: rlbench.action_modes.gripper_action_modes.Discrete

train_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 32
  shuffle: True
  num_workers: 4

val_dataset:
  _target_: lib.demo_dataset.DemoDataset
  variations: [0]
  demos_config:
    amount: 20
    image_paths: True
    dataset_root: data
    task_name: reach_target
    obs_config:
      _target_: rlbench.ObservationConfig
    random_selection: False
    from_episode_number: 100
  action_mode:
    _target_: rlbench.action_modes.action_mode.MoveArmThenGripper
    arm_action_mode:
      _target_: rlbench.action_modes.arm_action_modes.EndEffectorPoseViaIK
      absolute_mode: False
      # frame: world
      # collision_checking: False
    gripper_action_mode:
      _target_: rlbench.action_modes.gripper_action_modes.Discrete

val_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 32
  shuffle: True
  num_workers: 4

model:
  _target_: lib.bcz_model.BCZModel
  vision_network:
    _target_: lib.film_resnet.film_resnet18
    task_embed_dim: 768

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001

train:
  epochs: 10